### ISSUE TITLE
OMXplayer does not quit after playing

### ISSUE THREAD

**Issue by PS11011010** [popcornmix/omxplayer#266]
I use Qt for starting OMXplayer:

```
QString prog = "/usr/bin/omxplayer";
QStringList args;
...
QProcess *omxplayer = new QProcess();
omxplayer->startDetached(prog, args);
```

When I play multiple files one by one, OMX player does not quit after playing video. А problem seems to be similar [https://github.com/popcornmix/omxplayer/issues/12](OMXPlayer randomly hangs)

Linux raspberrypi 3.12.28+ #713 PREEMPT Fri Sep 19 16:43:32 BST 2014 armv6l GNU/Linux
firmware:e25efc4545d0cef7c49c82e770b3e4ccfc8aba4c
omxplayer Version   : 6ee9a0a [master]

**Comment by zevero** [comment]
This bug is still present. I am using omxplayer from a qt application running on rasperry-pi with arch. Everything is fine until I want to restart my app doing

           QProcess *restartProcess = new QProcess(this);
           restartProcess->startDetached("./start.sh"); //detached mode so we survive exit
           exit(0);

start.sh is doing some syncing of files and calling my qt application, which in turn will start omxplayer.

After this restart procedure omxplayer will not stop after video is finished. Even calling it manually from console will not quit until using key 'q' manually. Doing killall omxplayer or killall omxplayer.bin or killing my application an start scripts etc does not help.
Only after a complete reboot omxplayer will quit after playing a video.

**Comment by wackazong** [comment]
Also happens to me from the command line with this command on a raspberry pi 3 with the latest omxplayer from apt-get

omxplayer -d --aspect-mode fill --no-keys --win 0,25,720,460 --align center --no-ghost-box "https://r6---sn-8vq54vox2u-apne.googlevideo.com/videoplayback?expire=1473913172&dur=0.000&lmt=1280188504235337&key=yt6&ip=178.166.122.210&sver=3&id=o-AEjxs774sA5qX3Dtp1y5WOOwgs1Jb8dKQyPS4hVevomy&initcwndbps=2375000&source=youtube&mn=sn-8vq54vox2u-apne&mm=31&ratebypass=yes&requiressl=yes&ms=au&ei=9MzZV4_fIon1iAa_maOIDw&mv=m&mt=1473891201&pl=19&itag=43&mime=video%2Fwebm&ipbits=0&sparams=dur%2Cei%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&upn=D0ti009uHGc&signature=AAE4A1CC56437392BB80C4263F0DEB82C3AF55B5.58B2650B5F82A294083DF95ECAC79B1074D72548"

**Comment by zevero** [comment]
I am using it on raspberry pi 3 for arch with latest updates.
In my situation I am restarting my app via a loop in a script by simple exiting.

Most interestingly omxplayer is fine in the restarted app only I there is no other activity in my script. I can even insert sleep 30. But I can not call gpio or do some rsync.

It is beyond me why these actions influence the quiting behavior of omxplayer...

**Comment by popcornmix** [comment]
@wackazong your link doesn't work for me.
Providing a sample file or link that works would be helpful for me to reproduce the issue.

**Comment by wackazong** [comment]
@popcornmix It's a youtube resource link generated with youtube-dl. Problem is that the behaviour only occurs with some resource files.

**Comment by popcornmix** [comment]
Does it fail every time you get a link for that video?
Can you explain what you entered to get that link?

**Comment by wackazong** [comment]
I did not try.

You get a link by installing youtube-dl and executing

youtube-dl -f "best[vcodec!=vp9][height<=480]/best[vcodec!=vp9]" -g http://youtube.com/watch?v=EjAoBKagWQA

**Comment by Aiexis** [comment]
Hi all
I have the same issue with the last build (Git version: dfea8c9) and also a new version builded.
I use a simple php script to play mp3 files all day long. This issue appears randomly after a few hours or days.
omxplayer doesn't quit, so the script waits for the end of the mp3 infinitely.

The two solutions i've found:
- reboot ( :( )
- sudo pkill -f dbus

I've added this second solution to my script 
I've though about a dbus issue because I use it to check position (with "dbuscontrol.sh status") and when omxplayer hangs, it gives an error after 15 seconds (something like "no connection" but I don't remember exactly).

**Comment by jehutting** [comment]
Looks like you are running into #437.
The work-around seems to be adding the option '--no-osd'.
If you are willing to share the code (perhaps only by PM)...

**Comment by Aiexis** [comment]
Hi jehutting, thank you for your reply.
I'm trying this option right now. I will let you know if it works in a few hour, days... 

Concerning the script, it's something like:
- reading a distant database for "what to play"
- check if mp3 are present on the sd
- play each file with omxplayer

I've also build an homemade crossfade system (2 omxplayer, the second being launched when the position of the first is near to the end, tested with dbuscontrol), but I have disabled this system to be sure it's not related to this issue.

So, nothing spectacular here, but if you really want to, I will send you this function.

Thank you again ;)

**Comment by Aiexis** [comment]
I would like to add that there isn't any issue on another rasperry pi (with the same mp3 loop script).
- raspberry pi B+ 512MB
- omxplayer - Commandline multimedia player for the Raspberry Pi
        Build date: Sat, 27 Jun 2015 00:49:24 +0000
        Version   : 843744e [master]
- Linux raspberrypi 3.18.5+ #744 PREEMPT Fri Jan 30 18:19:07 GMT 2015 armv6l GNU/Linux
- Uptime: 21:51:11 up 37 days, 13:18, 0 users, load average: 0.05, 0.07, 0.06

Yes, it's not up to date, but it works fine ;)

**Comment by KenT2** [comment]
It looks like you are detecting the end of the track by using the dbus get_position. What might be happening is that sometimes you are calling get_position after the track has finished and the omxplayer has died.
I found it necessary to test whether omxplayer was alive immediately before calling get_position and to not call get_position if the process is dead. Also to put a try/except around the get_position as there is still a race condition in the small time between testing the process and calling get_position.

My latest effort at a dbus interface has played two 2 minute concurrent videos without hanging for 24 hours: (https://github.com/KenT2/pipresents-gapless/blob/master/pp_omxdriver.py)

**Comment by Aiexis** [comment]
Hi KenT2, thank you for your interest.
In my script, I test the return of dbuscontrol.sh status, like this;

exec("$dir/dbuscontrol.sh status $dbus 2>&1",$return) ;
if (!strstr($return[0]," was not provided by any .service files")) {
    * test position, duration etc... *      

} else {
	exec("sudo pkill omxplayer");
}

So i'm testing if dbus is returning something usefull, and if not, I kill omxplayer.
Maybe there's a lot of more elegant solutions, but this one works in most cases.

Anyway, for this issue, I've just changed my script for something very simple like
foreach ($file) exec("omxplayer ...")

And well, it seems to work with the --no-osd parameter since 3 hours... 
And i'm facing this issue only with mp3 files. 

Thank you for your script, I'm looking on it but I'm not sure to understand what's the point of it.

**Comment by jehutting** [comment]
Thanks @Aiexis and @KenT2 for sharing the info.

It is hard to tell why the 'old' RPI just works, as there is a lot in between: firmware/ffmpeg/omxplayer/model/etc. 

@KenT2 do you have reports from PiPresents users reporting this issue? Is it simple to replicate your test rig?
@Aiexis If I can have your script I will run it on the model you are using.

**Comment by Aiexis** [comment]
Ok @jehutting I will provide you a simplified script. I have to adapt it to be directly useable without database, log system etc.... And I have to test it a few hours to be sure it crashes !

**Comment by Aiexis** [comment]
@jehutting here you can download some stuff:
http://5.135.189.207/test/debug.tar
2 musics included, dbuscontrol.sh (modified to have dbus name in argument) and a php script.
For some reasons (don't remember exactly !) you have to use sudo to run it (sudo php debugdbus.php )

However, it runs without error for an hour now. I hope it crashes soon :)

**Comment by jehutting** [comment]
Hi @Aiexis,
Thanks for the script, and yeah strange things happens, also with --no-osd :-). Sometimes I end up with 4 omxplayer running at a time ...ha ha ha...definitely not good.

I changed dbuscontrol.sh :
```
OMXPLAYER_DBUS_ADDR="/tmp/omxplayerdbus.${USER:-root}"
OMXPLAYER_DBUS_PID="/tmp/omxplayerdbus.${USER:-root}.pid"
```
to get rid of the sudo need for the dbuscontrol call.
Added _php_ the first line of your php script so that one is now
```
<?php
```
and calling ```./dbuscontrol.sh```in stead of the one in the /home/pi, the user I don't have.

Nice songs by the way...

**Comment by Aiexis** [comment]
Hi @jehutting and thanks :+1: 
yes, it's a good news that strange things happens because this script still plays since yesterday on my Pi (without --no-osd). But I know it can works several days before freezing.
And yes when omxplayer fails to stop, there are 3 or 4 omxplayer in the process list. At this point, a "sudo pkill dbus" command unblocks the situation.... temporarily.

Sorry for the php short tag, I forgot this.

So, does the modification of dbuscontrol.sh changes something ? I mean, this issue is related to sudo use ?

Thanks again and happy new year ;-)

**Comment by jehutting** [comment]
First, best wishes for 2017!

@Aiexis : I don't think the use of sudo is related to this issue. Even without the sudo I ran into troubles.

I have to come back on my thinking this issue was related to issue 437 (with solution --no-osd I still ran into troubles). 

My problem with the script was caused by having ```audio_pwm_mode=2``` in ```/boot/config.txt```.
When commenting this line out, the php-script ran for hours without a problem.

With the (still?) experimental audio driver I got the same dbus message as Aiexis described in his/her first post. The logging (in below view with test2.mp3 with a 19.487 sec duration) revealed that the EOS (End-Of-Stream, the indication that the playing is completed) fails:

```
﻿11:06:52.549 T:18446744071772113974   DEBUG: Setting up display
11:07:06.943 T:18446744071786508222    INFO: COMXAudio::SubmitEOS
11:07:32.500 T:18446744071812065774    INFO: COMXAudio::IsEOS   <<<---took too long
11:07:32.669 T:18446744071812234500   DEBUG: have a nice day ;)
```

A good omxplayer2 run gives
```
11:07:32.475 T:18446744071812040553   DEBUG: Setting up display
11:07:46.961 T:18446744071826526691    INFO: COMXAudio::SubmitEOS
11:07:52.341 T:18446744071831906197    INFO: COMXAudio::IsEOS
11:07:52.530 T:18446744071832095289   DEBUG: have a nice day ;)
```
In this case this omxplayer2 instance -playing test2.mp3- isn't finished whereas an omxplayer1 instance -playing test1.mp3- is already created and playing as the script only sleeps for the duration of test2.mp3 (minus 5 secs for the fading time). The script also doesn't wait till omxplayerX is actually finished.

When the failing EOS occurs it takes more time for omxplayer2 to finish; in my case it even exceeded the time needed for omxplayer1 to finish! So when the script starts a new omxplayer2 (instance), the previous omxplayer2 (instance) is still running! 

The new omxplayer2 tries to claim the dbus name org.mpris.Mediaplayer2.omxplayer2 but as this name is still occupied by the 'faulty/hanging' omxplayer2, it gets the alternative name org.mpris.Mediaplayer2.omxplayer2.instance<PID>. As the php script isn't aware of this alternative name, it still sends it duration/position requests to org.mpris.Mediaplayer2.omxplayer2. Now, when the 'faulty' omxplayer2 actually ends, the dbus service on org.mpris.Mediaplayer2.omxplayer doesn't exist any more. This leads to the dbus error message and exiting of the script.

By the way, with ```audio_pwm_mode=2``` and when I create 2 ssh sessions, and each playing a test.mp3, OMXPlayer is really dreadful stuttering... 

Hope that this all makes sense :-)

@popcornmix : Is this failing EOS a known firmware / experimental audio driver issue?

**Comment by Aiexis** [comment]
Hello @jehutting 
Thank you for your testings !
You're right, my homemade crossfade system is not compatible with the audio_pwm_mode. I've wrote a post a few weeks ago on the rasperrypi.org forum:
https://www.raspberrypi.org/forums/viewtopic.php?p=1082723#p1082723

It is commented out on my config.txt but I'm still facing the issue... but not with the script I've uploaded for you ! This one ran several days and I have stopped it.

So we have the same consequence (dbus error message) but not for the same reason.

In my investigations, I found that the logging system (meaning: send an information to a database when a mp3 file is ready to be played) that I have deleted for the little script causes the issue. Weird isn't it ?
And this is not all: just remplacing the logging by a simply "sleep(3)" causes the same issue !

Can you believe that ? When PHP is just waiting between 2 tracks, it makes dbus become unresponsible.

Please have a look at this new script:
http://5.135.189.207/test/debug2.tar
dbuscontrol.sh has been corrected, so no need of sudo any more.
in the php script (start.php), you will see at the end the line with the sleep(3) command, which causes the issue, after 25 - 90 loops (tested about 20 times since monday).

And sorry in advance for the very annoying track this time, it just has to be short ;)

I suppose that the "php sleep command causes omxplayer end file detection fails" is just a part of a more general problem, but I fear this is out of my competences :-(

**Comment by jehutting** [comment]
Hi @Aiexis,

Thanks for the info. Nice that jdb confirms the issue.
With the audio_pwm_mode=2 commented, your script runs without any issue (PLAYING 519 times). I even reduced the 'crossfade' sleep to 1, and commented the last sleep. So forcing two omxplayers crossing each other. The song played 4708 times when I stopped the script.

**Comment by Aiexis** [comment]
Hi @jehutting 
I was about to post again. I have formated my sd to install back raspbian jessie lite, and everything works without problem.

So i though there is something in my setup that makes omxplayer freeze... I have re-installed all the packages I need, and at the end... it still works.

Before that, I made a copy (with win32disk imager) of the faulty system on my PC drive, and I have restored it on the same sd.

And... now it works.

This is sorcery :-(

i'm giving up :-(

Sorry for this time wasting...

**Comment by jehutting** [comment]
@Aiexis I'm glad that you got your system up and running well :-)
Good luck with your project, and hopefully I see your project publicated :+1: (post a link in case you do!)

**Comment by Aiexis** [comment]
I really would have preferred to know what happened before, but you're right, it's running well now... until next time !

Thank you for your wishes ;)  It's just a small project to crossmix titles automatically (crossfades times are pre-calculated in a database because raspberry pi is far too slow to calculate this realtime). 
I think there is no interest except for me and my ears ^^ 

I will let you know if this issue occurs again and I will try to ckeck precisely what was changed in the configuration somewhere just before...
