### ISSUE TITLE
Cross Compile libssh and libsmbclient

### ISSUE THREAD

**Issue by fcarlier** [popcornmix/omxplayer#267]
Hello,

With your last modify in ffmeg, you introduce --enable-libssh and --enable-libsmbclient

But in my cross-toolchain, i don't have libssh-dev and libsmbclient-dev
I don't want 'apt-get install' but cross-compile ;)

Have you a two Makefile ? 
more dependancies is equal more cross-compile ;)

THX and See you later

**Comment by Ruffio** [comment]
@fcarlier is this still an issue?

**Comment by popcornmix** [comment]
Not an omxplayer issue.
You should be able to build omxplayer natively on the Pi, and there is a good build environment here: https://github.com/skgsergio/rpi-buildenv
You can also change the ffmpeg configure options to not require ssh and libsmbclient if you don't need them.
Otherwise you need to get the source of libssh and libsmbclient, cross compile those, and make sure they are on the include/link paths of omxplayer. But that is beyond the scope of what omxplayer is for.
