### ISSUE TITLE
omxplayer seems to play then hangs on

### ISSUE THREAD

**Issue by jrowebster** [popcornmix/omxplayer#272]
Hi,
I have a raspberry pi model b installed with the latest raspbian image. I try to play a rtmp stream with omxplayer but i get a black screen every time on my tv connected via hdmi to my pi. i have downloaded the stream with rtmpdump and tried to open it with omxplayer -o hdmi command but omxplayer just hanged on forever. this is the test file from the stream: https://www.dropbox.com/s/ql1migeac8spi2s/stream.flv?dl=0  
can you please download it and try to play with omxplayer via hdmi? 
mediainfo output _videocodecid: avc1 _audiocodecid : mp4a
omxplayer version
Build date: Sat, 22 Mar 2014 20:58:15 +0000
Version   : 39e6342 [master]
thanks

**Comment by deborah-c** [comment]
Baseline is not (as one might expect) a subset of main profile, but allows a number of (somewhat complicated) error recovery features to be turned on. Constrained baseline just means the intersection of baseline and main profiles, and won't cause problems in the least. The problem here appears to be container-related; I'll take a look shortly.

**Comment by popcornmix** [comment]
Can you try updating firmware (with rpi-update) and testing your stream?

**Comment by popcornmix** [comment]
This is believed to be fixed. Please reopen if there is still a problem.
