### ISSUE TITLE
Broken libraries under Arch Linux ARM

### ISSUE THREAD

**Issue by kalsan** [popcornmix/omxplayer#432]
Since latest update (Feb 28 2016) omxplayer ("omxplayer-git") is no longer working under Arch Linux ARM. At least the following dependencies are broken:
-> libavcodec.so.56 (now 57)
-> libavformat.so.56 (now 57)
-> libavutil.so.54 (now 55)

**Comment by jehutting** [comment]
@kalsan Is this something to be fixed by the Arch Linux maintainers?
I don't how it works on Arch Linux. [Here](https://archlinuxarm.org/packages/armv6h/omxplayer-git/log) I see that they don't build the ffmpeg libs? Another package?
Anyway, I don't think this (popcornmix) omxplayer repository will be of any help on this?

**Comment by kalsan** [comment]
The broken dependencies were fixed in early March. Sorry I forgot to close the issue.

**Comment by jehutting** [comment]
Thanks!
