### ISSUE TITLE
REQUEST: Is it possible to have omxplayer  in a single binary without dependencies?

### ISSUE THREAD

**Issue by fredericofs** [popcornmix/omxplayer#483]
I my raspbian omxplayer depends of samba-libs, and it seems difficult to add omxplayer to buildroot systems. Would it be feasible to build omxplayer into a single binary , without external dependencies?

**Comment by popcornmix** [comment]
Everything is possible, but it's not something I am going to work on.
Assuming you can build omxplayer, you can either configure it without support for the external libraries that cause you problems. E.g. ``--disable-libsmbclient``. You may also want ``--disablelibssh`` and ``--disable-openssl``.
The other option is to statically link to the libraries (i.e. link with the ``.a`` library rather than the ``.so``).

**Comment by nagualcode** [comment]
how can I static compile omxplayer?
