### ISSUE TITLE
Skipping/Flashing video on 2nd loop

### ISSUE THREAD

**Issue by pete001** [popcornmix/omxplayer#508]
Hi, i have found a curious issue with `--loop` where the video plays perfectly on the first loop: 

```
omxplayer --loop --aidx -1 video_with_loop_issue.mkv
Video codec omx-h264 width 1920 height 1080 profile 578 fps 25.000000
Subtitle count: 0, state: off, index: 1, delay: 0
V:PortSettingsChanged: 1920x1080@25.00 interlace:0 deinterlace:0 anaglyph:0 par:1.00 display:0 layer:0 alpha:255 aspectMode:0
```

But on subsequent loops, the video flickers and flashes on screen. On the command line, i see the following echoed to stdout many times:

```
V:PortSettingsChanged: 1920x1080@25.00 interlace:-1 deinterlace:0 anaglyph:0 par:1.00 display:0 layer:0 alpha:255 aspectMode:0
```

The only difference with the initial run is `interlace:-1` im not sure if this is relevant though. 

You can try the file here: https://hawkr.io/test/video_with_loop_issue.mkv

To confirm, im using the latest version: 

```
        Build date: Fri, 23 Sep 2016 00:56:49 +0000
        Version   : dfea8c9 [master]
        Repository: https://github.com/popcornmix/omxplayer.git
```

**Comment by jehutting** [comment]
My RPI3 loops your mkv just fine, without skipping or flashing.
Neither got the multiple V:PortSettingsChanged output; just once at the start. Did not investigated yet why you get it or omxplayer detects a change of interlace.mode.

**Comment by pete001** [comment]
Ah interesting - im using a RPi3 too. Could you please try with the following options: 

```
omxplayer -t off -b --loop --no-osd --orientation 0 --aidx -1 video_with_loop_issue.mkv
```

These are my usual settings, i will try a different RPi and monitor too, see if that helps.

**Comment by jehutting** [comment]
AAAAAHHHH... I got a white flash at the end of the **first** loop too.
And it is not due to the extra options. After I stripped all extra options (so ending up to your first post command) I still kept the white flash. Unbelievable that I missed it when running the loops before. Sorry for that Pete!

The fix for the white flash is what I tried to get pulled in in #455. (Although it is not up-to-date, the branch **loop** still exists in my own omxplayer repository).

**Comment by jehutting** [comment]
AAAAAHHHH...yes a second time... I now see that this video is not the same as in issue 506.
Now I get the multiple V:PortSettingsChanged too. Another (bigger) sorry for Pete!

The -t option is for the subtitle index selection. Default the subtitle viewing is off. The argument value ``off`` has no meaning; it only results in showing the subtitle with index 0 (zero) if your video has subtitles or if you use an external .srt subtitle file.

About orientation, this _COMXStreamInfo_ member is not initialized (COMXStreamInfo::Clear). So supplying this option ensures the OMX_DISPLAY_ROT0 format (see _OMXVideo::Open_).

When during the video play the port settings changes (due to _OMX_EventPortSettingsChanged_ or _OMX_EventParamOrConfigChanged_, _whatever that be_) the interlace.emode shown in the logging is -1, as it is not being read from the decoder (as done in the opening of decoder).

My white flash fix doesn't solve the flashing on start of the second loop. Needs further investigation.

**Comment by pete001** [comment]
Ah great, this makes sense - i have seen a white flash at the end of the first loop before, but this was a different issue to what i was seeing, but it looks like you have been able to replicate that now which is good. 

Thanks so much for continuing to test this, i really appreciate it. I can easily replicate a test rig on any commit hash/branch if you need me to test something - just let me know.

**Comment by jehutting** [comment]
Hi Pete,

My white flash does fix it (at least today it does :-).

Created a [debian package](https://github.com/jehutting/omxplayer/releases/tag/SkippingAndFlashingFix) which you could try out. Of course, be sure to have a SD backup before installing it.

**Comment by pete001** [comment]
Hi Jozef, i can confirm that definitely fixes the white flash for me, thanks for pushing that deb up 😄

**Comment by jehutting** [comment]
Hi Pete, Thanks for checking it. Nice that it works.
@popcornmix: if you can confirm the issue and the fix, I will push a pull-request.

**Comment by pete001** [comment]
Hi @jehutting,

I've extensively tested your flash fix branch for the last 2 weeks and i can report that ive found no issues with it via 24/7 playback over 14 days 😄 

I will be using this fork until it gets merged into the master branch. 

Thanks again!

**Comment by Ruffio** [comment]
@jehutting Why not just submit the PR? Then I think it is easier to see the changed code thereby making it easier to 'validate'?

**Comment by jehutting** [comment]
Hi @pete001 Thanks for the info. Good to now that it works.

@Ruffio & @popcornmix It is the same branch I used for PR #455.
I only updated it to the latest version, just for Pete.

**Comment by OMID-313** [comment]
Dear @jehutting and @popcornmix 
Is this fix available in the latest release?
And is it available via `apt-get` !?

**Comment by jehutting** [comment]
See PR no. 455. Having any trouble with the latest github version?
If so try to post the video.
