### ISSUE TITLE
Analysing Audio data

### ISSUE THREAD

**Issue by flatt3rn** [popcornmix/omxplayer#700]
Hello, i try to modify the omxplayer for a project where i want to analyse the music while its playing. 
I am searching for the code where the actual music data is processed, to analyse it there. Maybe some of you know the code very well and know which class is responsible for it.

I checked the data going through OMXPlayerAudio::Decode and compared it with the real file.
https://github.com/popcornmix/omxplayer/blob/b4bbef8fac5e8c2ddafa895f98456ba715b39c6b/OMXPlayerAudio.cpp#L224
The data_dec stores the encoded data.

So i assume that decoded stores the decoded data. Am i right?
https://github.com/popcornmix/omxplayer/blob/b4bbef8fac5e8c2ddafa895f98456ba715b39c6b/OMXPlayerAudio.cpp#L242

**Comment by popcornmix** [comment]
I'm not sure if omxplayer is the best starting point for a audio analysis project (it's predominantly a video player).
omxplayer just uses ffmpeg for audio decode. I would have thought using ffmpeg directly for decode and alsa if you want to hear it might be better.

But yes, ``data_dec`` contains the encoded audio data from the demuxer and ``decoded`` contains the decoded audio data returned from ffmpeg.

**Comment by flatt3rn** [comment]
Ok thanks. Do you know which format the decoded data has? 
I found AV Comfort Noise as codec, but i tried to save it as a file and add the corresponding headers, but all i got was noise. (Just for testing purposes)

**Comment by popcornmix** [comment]
I believe the decoded format will eithr be AV_SAMPLE_FMT_S16 or AV_SAMPLE_FMT_FLTP (based on what ffmpeg decodes to).

But you have a requirement to use ffmpeg to decode audio for your own analysis.
Just because omxplayer also uses ffmpeg for audio decode doesn't mean it's the right tool for the job.
You'd be better off creating a [forum post](https://www.raspberrypi.org/forums/viewforum.php?f=38) describing exactly what you trying to do and what the problems to get support.
