### ISSUE TITLE
Raspbian desktop compatibility?

### ISSUE THREAD

**Issue by matteoraggi** [popcornmix/omxplayer#707]
Is omxplayer compatible with Raspbian desktop too?
https://www.raspberrypi.org/downloads/raspberry-pi-desktop/

**Comment by edrozenberg** [comment]
The pre-built omxplayer binaries (built for -arm) won't work on x86 platforms. For ex. copying the omxplayer files from the Raspbian Raspberry Pi image won't work on x86 (PC/Mac). Overall not sure if omxplayer is meant to or can run on x86. Might be easier to stick to using mplayer or vlc in console mode if you're trying to avoid using X.

The omxplayer source code build process looks for Raspberry-Pi related firmware files in /opt/vc so that part of the build will fail on x86.

If you want to try modifying the build process, the steps would include:

1. Install the FreeFont font package if not already installed (used for on-screen controls and subtitles)
2. Download the omxplayer source code from github
3. Modify Makefile as necessary - for ex. removing the pieces that look for /opt/vc. And adding any additional include paths to find the include files it needs. In my case (Slackware ARM) I needed to add `-I /usr/lib/dbus-1.0/include` to the include path
4. Run the make, for ex. `make ffmpeg; make -j4`. If successful, the app files will be generated and zipped as file `omxplayer-dist.tgz`
5. Create a script similar to below - some parts may not be needed/applicable on some OS's. This is what I needed on Slackware ARM:

```
( cd usr/bin ; rm -rf fbset )
( cd usr/bin ; ln -sf /usr/sbin/fbset fbset )

( cd usr/share/fonts/truetype/freefont ; rm -rf FreeMono.ttf )
( cd usr/share/fonts/truetype/freefont ; ln -sf /usr/share/fonts/TTF/FreeMono.ttf FreeMono.ttf )
( cd usr/share/fonts/truetype/freefont ; rm -rf FreeMonoBold.ttf )
( cd usr/share/fonts/truetype/freefont ; ln -sf /usr/share/fonts/TTF/FreeMonoBold.ttf FreeMonoBold.ttf )
( cd usr/share/fonts/truetype/freefont ; rm -rf FreeMonoBoldOblique.ttf )
( cd usr/share/fonts/truetype/freefont ; ln -sf /usr/share/fonts/TTF/FreeMonoBoldOblique.ttf FreeMonoBoldOblique.ttf )
( cd usr/share/fonts/truetype/freefont ; rm -rf FreeMonoOblique.ttf )
( cd usr/share/fonts/truetype/freefont ; ln -sf /usr/share/fonts/TTF/FreeMonoOblique.ttf FreeMonoOblique.ttf )
( cd usr/share/fonts/truetype/freefont ; rm -rf FreeSans.ttf )
( cd usr/share/fonts/truetype/freefont ; ln -sf /usr/share/fonts/TTF/FreeSans.ttf FreeSans.ttf )
( cd usr/share/fonts/truetype/freefont ; rm -rf FreeSansBold.ttf )
( cd usr/share/fonts/truetype/freefont ; ln -sf /usr/share/fonts/TTF/FreeSansBold.ttf FreeSansBold.ttf )
( cd usr/share/fonts/truetype/freefont ; rm -rf FreeSansBoldOblique.ttf )
( cd usr/share/fonts/truetype/freefont ; ln -sf /usr/share/fonts/TTF/FreeSansBoldOblique.ttf FreeSansBoldOblique.ttf )
( cd usr/share/fonts/truetype/freefont ; rm -rf FreeSansOblique.ttf )
( cd usr/share/fonts/truetype/freefont ; ln -sf /usr/share/fonts/TTF/FreeSansOblique.ttf FreeSansOblique.ttf )
( cd usr/share/fonts/truetype/freefont ; rm -rf FreeSerif.ttf )
( cd usr/share/fonts/truetype/freefont ; ln -sf /usr/share/fonts/TTF/FreeSerif.ttf FreeSerif.ttf )
( cd usr/share/fonts/truetype/freefont ; rm -rf FreeSerifBold.ttf )
( cd usr/share/fonts/truetype/freefont ; ln -sf /usr/share/fonts/TTF/FreeSerifBold.ttf FreeSerifBold.ttf )
( cd usr/share/fonts/truetype/freefont ; rm -rf FreeSerifBoldItalic.ttf )
( cd usr/share/fonts/truetype/freefont ; ln -sf /usr/share/fonts/TTF/FreeSerifBoldItalic.ttf FreeSerifBoldItalic.ttf )
( cd usr/share/fonts/truetype/freefont ; rm -rf FreeSerifItalic.ttf )
( cd usr/share/fonts/truetype/freefont ; ln -sf /usr/share/fonts/TTF/FreeSerifItalic.ttf FreeSerifItalic.ttf )

**Comment by popcornmix** [comment]
Closing as omxplayer isn't designed for x86. There are many alternative video platyers on x86.
